version: '2'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - /var/local/docker/volumes/mongo/data/db:/data/db
      - /var/local/docker/volumes/mongo/data/configdb:/data/configdb