version: '2'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - /var/local/docker/volumes/mongo/data/db:/data/db
      - /var/local/docker/volumes/mongo/data/configdb:/data/configdb

  springrest:
    image: restapi
    container_name: restapi
    volumes:
      - /logs/infra:/logs
    ports:
      - 8090:8090
    environment:
      - PROFILE = development
    depends_on:
      - mongo
